/* Generated By:JavaCC: Do not edit this line. BIFv015Constants.java */
/* This parser uses the data structures in the JavaBayes core *
 * engine (package BayesianNetworks); other implementations   *
 * may use different data structures                          */
package Parsers.BIFv015;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BIFv015Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 7;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 8;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 9;
  /** RegularExpression Id. */
  int NETWORK = 10;
  /** RegularExpression Id. */
  int VARIABLE = 11;
  /** RegularExpression Id. */
  int PROBABILITY = 12;
  /** RegularExpression Id. */
  int PROPERTY = 13;
  /** RegularExpression Id. */
  int VARIABLETYPE = 14;
  /** RegularExpression Id. */
  int DISCRETE = 15;
  /** RegularExpression Id. */
  int DEFAULTVALUE = 16;
  /** RegularExpression Id. */
  int TABLEVALUES = 17;
  /** RegularExpression Id. */
  int NON_NEGATIVE_NUMBER = 18;
  /** RegularExpression Id. */
  int EXPONENT = 19;
  /** RegularExpression Id. */
  int STRING = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\",\"",
    "<SINGLE_LINE_COMMENT>",
    "<FORMAL_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"network\"",
    "\"variable\"",
    "\"probability\"",
    "\"property\"",
    "\"type\"",
    "\"discrete\"",
    "\"default\"",
    "\"table\"",
    "<NON_NEGATIVE_NUMBER>",
    "<EXPONENT>",
    "<STRING>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"|\"",
  };

}
