/*
 * Copyright (C) 2015 Dieter J Kybelksties
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *
 * @author  Dieter J Kybelksties
 * @date May 11, 2016
 *
 */
package BayesGUI;

import BayesianInferences.InferenceGraph;
import BayesianInferences.InferenceGraphNode;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;

/**
 *
 * @author Dieter J Kybelksties
 */
public class EditVariableDialog extends javax.swing.JDialog
{

    private static final Class CLAZZ = InferenceGraphNode.class;
    private static final String CLASS_NAME = CLAZZ.getName();
    private static final Logger LOGGER = Logger.getLogger(CLASS_NAME);

    JPopupMenu valueTablePopup;

    /**
     * Creates new form EditVariableDialog
     *
     * @param parent
     * @param graph
     * @param node
     */
    public EditVariableDialog(java.awt.Frame parent,
                              InferenceGraph graph,
                              InferenceGraphNode node)
    {
        super(parent, true);
        initComponents();
        try
        {
            ValueTableModel model = new ValueTableModel(
                            graph.getBayesNet().getFunction(node.getName()));
            valueTable.setModel(model);
        }
        catch (Exception ex)
        {
            LOGGER.log(Level.SEVERE, null, ex);
        }
        JMenuItem menuItem;
        ActionListener action = new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                String command = e.getActionCommand().toUpperCase();
                int[] rows = valueTable.getSelectedRows();
                switch (command)
                {
                    case "ADD":
                        ((ValueTableModel) valueTable.getModel()).add("");
                        break;
                    case "REMOVE":
                        ((ValueTableModel) valueTable.getModel()).remove(rows);
                        break;
                }
            }
        };
        valueTablePopup = new JPopupMenu();

        menuItem = new JMenuItem("Add");
        menuItem.addActionListener(action);
        valueTablePopup.add(menuItem);

        menuItem = new JMenuItem("Remove");
        menuItem.addActionListener(action);
        valueTablePopup.add(menuItem);
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        valueTableScrollPane = new javax.swing.JScrollPane();
        valueTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        valueTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        valueTable.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                valueTableMouseClicked(evt);
            }
        });
        valueTableScrollPane.setViewportView(valueTable);

        getContentPane().add(valueTableScrollPane);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void valueTableMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_valueTableMouseClicked
    {//GEN-HEADEREND:event_valueTableMouseClicked
        valueTable.setComponentPopupMenu(valueTablePopup);
    }//GEN-LAST:event_valueTableMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable valueTable;
    private javax.swing.JScrollPane valueTableScrollPane;
    // End of variables declaration//GEN-END:variables
}
