/*
 * @author  Dieter J Kybelksties
 * @date Jul 8, 2016
 *
 */
package BayesGUI;

import BayesianInferences.InferenceGraph;
import BayesianInferences.InferenceGraphNode;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JMenuItem;
import javax.swing.JPopupMenu;

/**
 *
 * @author Dieter J Kybelksties
 */
public class EditVariableDialog extends javax.swing.JDialog
{

    JPopupMenu valueTablePopup;

    /**
     * Creates new form EditVariableDialog
     *
     * @param parent
     * @param graph
     * @param node
     */
    public EditVariableDialog(java.awt.Frame parent,
                              InferenceGraph graph,
                              InferenceGraphNode node)
    {
        super(parent, true);
        initComponents();
        ValueTableModel model = new ValueTableModel(
                        graph.getBayesNet().getFunction(node.getName()));
        valueTable.setModel(model);
        JMenuItem menuItem;
        ActionListener action = new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                String command = e.getActionCommand().toUpperCase();
                int[] rows = valueTable.getSelectedRows();
                switch (command)
                {
                    case "ADD":
                        ((ValueTableModel) valueTable.getModel()).add("");
                        break;
                    case "REMOVE":
                        ((ValueTableModel) valueTable.getModel()).remove(rows);
                        break;
                }
            }
        };
        valueTablePopup = new JPopupMenu();

        menuItem = new JMenuItem("Add");
        menuItem.addActionListener(action);
        valueTablePopup.add(menuItem);

        menuItem = new JMenuItem("Remove");
        menuItem.addActionListener(action);
        valueTablePopup.add(menuItem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        valueTableScrollPane = new javax.swing.JScrollPane();
        valueTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        valueTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        valueTable.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                valueTableMouseClicked(evt);
            }
        });
        valueTableScrollPane.setViewportView(valueTable);

        getContentPane().add(valueTableScrollPane);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void valueTableMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_valueTableMouseClicked
    {//GEN-HEADEREND:event_valueTableMouseClicked
        valueTable.setComponentPopupMenu(valueTablePopup);
    }//GEN-LAST:event_valueTableMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable valueTable;
    private javax.swing.JScrollPane valueTableScrollPane;
    // End of variables declaration//GEN-END:variables
}
