/*
 * @author  Dieter J Kybelksties
 * @date Jul 1, 2016
 *
 */
package BayesGUI;

import BayesianInferences.InferenceGraph;
import BayesianInferences.InferenceGraphNode;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Dieter J Kybelksties
 */
public class EditProbabilitiesDialog extends javax.swing.JDialog
{

    int numValues = 0;

    class MyTableCellRenderer extends DefaultTableCellRenderer
    {

        @Override
        public Component getTableCellRendererComponent(JTable table,
                                                       Object value,
                                                       boolean isSelected,
                                                       boolean hasFocus,
                                                       int row,
                                                       int column)
        {
            Component c = super.getTableCellRendererComponent(table,
                                                              value,
                                                              isSelected,
                                                              hasFocus,
                                                              row,
                                                              column);
            if ((row / numValues) % 2 == 0)
            {
                c.setBackground(Color.WHITE);
                c.setForeground(Color.BLACK);
                if (column == 0 || column == table.getColumnCount() - 1)
                {
                    c.setForeground(Color.BLUE);
                }
                if (column == table.getColumnCount() - 1)
                {
                    c.setBackground(Color.GREEN);
                }
            }
            else
            {
                c.setBackground(Color.GRAY);
                c.setForeground(Color.WHITE);
                if (column == 0 || column == table.getColumnCount() - 1)
                {
                    c.setForeground(Color.GREEN);
                }
                if (column == table.getColumnCount() - 1)
                {
                    c.setBackground(Color.BLUE);
                }
            }
            if (column == table.getColumnCount() - 1)
            {
                // set the probabilities that do not add up to 1.0 to red
                int set = row / numValues;
                double sum = 0.0;
                for (int setRow = 0; setRow < numValues; setRow++)
                {
                    sum += (Double) table.getValueAt(numValues * set + setRow,
                                                     table.getColumnCount() - 1);
                }
                if (sum != 1.0)
                {
                    for (int setRow = 0; setRow < numValues; setRow++)
                    {
                        Component c1 =
                                  super.getTableCellRendererComponent(
                                          table,
                                          value,
                                          isSelected,
                                          hasFocus,
                                          numValues *
                                          set +
                                          setRow,
                                          table.
                                          getColumnCount() - 1);
                        c1.setForeground(Color.RED);
                    }
                }
            }
            return c;
        }
    }

    /**
     * Creates new form EditProbabilitiesDialog
     *
     * @param parent
     * @param graph
     * @param node
     */
    public EditProbabilitiesDialog(java.awt.Frame parent,
                                   InferenceGraph graph,
                                   InferenceGraphNode node)
    {
        super(parent, true);
        initComponents();
        ProbabilityTableModel model = new ProbabilityTableModel(
                              graph.getBayesNet().getFunction(node.getName()));
        probabilityTable.setModel(model);
        probabilityTable.setDefaultRenderer(Object.class,
                                            new MyTableCellRenderer());
        numValues = model.getNumberOfValues();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        probabilityScrollPane = new javax.swing.JScrollPane();
        probabilityTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        probabilityTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        probabilityScrollPane.setViewportView(probabilityTable);

        getContentPane().add(probabilityScrollPane);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane probabilityScrollPane;
    private javax.swing.JTable probabilityTable;
    // End of variables declaration//GEN-END:variables
}
