/*
 * @author  Dieter J Kybelksties
 * @date Jul 1, 2016
 *
 */
package BayesGUI;

import BayesianInferences.InferenceGraph;
import BayesianInferences.InferenceGraphNode;

/**
 *
 * @author Dieter J Kybelksties
 */
public class EditProbabilitiesDialog extends javax.swing.JDialog
{

    /**
     * Creates new form EditProbabilitiesDialog
     *
     * @param parent
     * @param graph
     * @param node
     */
    public EditProbabilitiesDialog(java.awt.Frame parent,
                                   InferenceGraph graph,
                                   InferenceGraphNode node)
    {
        super(parent, true);
        initComponents();
        ProbabilityTableModel model = new ProbabilityTableModel(
                              graph.getBayesNet().getFunction(node.getName()));
        probabilityTable.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        probabilityScrollPane = new javax.swing.JScrollPane();
        probabilityTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        probabilityTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        probabilityScrollPane.setViewportView(probabilityTable);

        getContentPane().add(probabilityScrollPane);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane probabilityScrollPane;
    private javax.swing.JTable probabilityTable;
    // End of variables declaration//GEN-END:variables
}
