/*
 * @author  Dieter J Kybelksties
 * @date Jul 8, 2016
 *
 */
package BayesGUI;

import BayesianInferences.InferenceGraph;
import BayesianInferences.InferenceGraphNode;

/**
 *
 * @author Dieter J Kybelksties
 */
public class EditVariableDialog extends javax.swing.JDialog
{

    /**
     * Creates new form EditVariableDialog
     *
     * @param parent
     * @param graph
     * @param node
     */
    public EditVariableDialog(java.awt.Frame parent,
                              InferenceGraph graph,
                              InferenceGraphNode node)
    {
        super(parent, true);
        initComponents();
        ValueTableModel model = new ValueTableModel(
                        graph.getBayesNet().getFunction(node.getName()));
        valueTable.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        valueTableScrollPane = new javax.swing.JScrollPane();
        valueTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        valueTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        valueTableScrollPane.setViewportView(valueTable);

        getContentPane().add(valueTableScrollPane);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable valueTable;
    private javax.swing.JScrollPane valueTableScrollPane;
    // End of variables declaration//GEN-END:variables
}
