/*
 * @author  Dieter J Kybelksties
 * @date Jun 8, 2016
 *
 */
package BayesGUI;

import BayesianInferences.InferenceGraphNode;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;

/**
 *
 * @author Dieter J Kybelksties
 */
public class SetObservedVarDialog extends javax.swing.JDialog
{

    InferenceGraphNode node;

    boolean observed;

    /**
     * Creates new form SetObservedVarDialog
     *
     * @param parent
     * @param modal
     * @param node
     */
    public SetObservedVarDialog(JFrame parent,
                                boolean modal,
                                InferenceGraphNode node)
    {
        super(parent, modal);
        initComponents();
        this.variableNameLabel.setText(node.getName());
        this.node = node;
        DefaultListModel listModel = new DefaultListModel();
        String[] values = node.getValues();
        for (String value : values)
        {
            listModel.addElement(value);
        }
        valuesList.setModel(listModel);
        valuesList.setSelectedValue(node.getObservedIndex(), true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        valuesListScrollPane = new javax.swing.JScrollPane();
        valuesList = new javax.swing.JList();
        variableNameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Set observed value");

        valuesList.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                valuesListMouseClicked(evt);
            }
        });
        valuesListScrollPane.setViewportView(valuesList);

        getContentPane().add(valuesListScrollPane, java.awt.BorderLayout.CENTER);

        variableNameLabel.setText("jLabel1");
        getContentPane().add(variableNameLabel, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void valuesListMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_valuesListMouseClicked
    {//GEN-HEADEREND:event_valuesListMouseClicked
        node.setObservationValue((String) valuesList.getSelectedValue());
        if (evt.getClickCount() > 1)
        {
            setVisible(false);
        }
    }//GEN-LAST:event_valuesListMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList valuesList;
    private javax.swing.JScrollPane valuesListScrollPane;
    private javax.swing.JLabel variableNameLabel;
    // End of variables declaration//GEN-END:variables
}
