/*
 * Copyright (C) 2015 Dieter J Kybelksties
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *
 * @author  Dieter J Kybelksties
 * @date May 11, 2016
 *
 */
package BayesGUI;

import BayesianInferences.InferenceGraphNode;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;

/**
 * Dialog for setting the value of an observed variable.
 *
 * @author Dieter J Kybelksties
 */
public class SetObservedVarDialog extends javax.swing.JDialog
{

    private static final Class CLAZZ = SetObservedVarDialog.class;
    private static final String CLASS_NAME = CLAZZ.getName();
    private static final Logger LOGGER = Logger.getLogger(CLASS_NAME);

    InferenceGraphNode node;

    boolean observed;

    /**
     * Creates new form SetObservedVarDialog
     *
     * @param parent parent frame
     * @param modal  whether or not to display the dialog in modal form
     * @param node   the node which is to be set as observed
     */
    public SetObservedVarDialog(JFrame parent,
                                boolean modal,
                                InferenceGraphNode node)
    {
        super(parent, modal);
        initComponents();
        this.variableNameLabel.setText(node.getName());
        this.node = node;
        DefaultListModel listModel = new DefaultListModel();
        String[] values = node.getValues();
        for (String value : values)
        {
            listModel.addElement(value);
        }
        valuesList.setModel(listModel);
        valuesList.setSelectedValue(node.getObservedIndex(), true);

    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        valuesListScrollPane = new javax.swing.JScrollPane();
        valuesList = new javax.swing.JList();
        variableNameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Set observed value");

        valuesList.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                valuesListMouseClicked(evt);
            }
        });
        valuesListScrollPane.setViewportView(valuesList);

        getContentPane().add(valuesListScrollPane, java.awt.BorderLayout.CENTER);

        variableNameLabel.setText("jLabel1");
        getContentPane().add(variableNameLabel, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void valuesListMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_valuesListMouseClicked
    {//GEN-HEADEREND:event_valuesListMouseClicked
        node.setObservationValue((String) valuesList.getSelectedValue());
        if (evt.getClickCount() > 1)
        {
            setVisible(false);
        }
    }//GEN-LAST:event_valuesListMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList valuesList;
    private javax.swing.JScrollPane valuesListScrollPane;
    private javax.swing.JLabel variableNameLabel;
    // End of variables declaration//GEN-END:variables
}
