/* Generated By:JavaCC: Do not edit this line. BIFv01Constants.java */
package Parsers.BIFv01;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BIFv01Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NETWORK = 8;
  /** RegularExpression Id. */
  int VARIABLE = 9;
  /** RegularExpression Id. */
  int PROBABILITY = 10;
  /** RegularExpression Id. */
  int PROPERTY = 11;
  /** RegularExpression Id. */
  int VARIABLETYPE = 12;
  /** RegularExpression Id. */
  int DISCRETE = 13;
  /** RegularExpression Id. */
  int DEFAULTVALUE = 14;
  /** RegularExpression Id. */
  int TABLEVALUES = 15;
  /** RegularExpression Id. */
  int PROPERTYSTRING = 16;
  /** RegularExpression Id. */
  int WORD = 17;
  /** RegularExpression Id. */
  int LETTER = 18;
  /** RegularExpression Id. */
  int DIGIT = 19;
  /** RegularExpression Id. */
  int NUMBER = 20;
  /** RegularExpression Id. */
  int EXPONENT = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\",\"",
    "\"network\"",
    "\"variable\"",
    "\"probability\"",
    "\"property\"",
    "\"type\"",
    "\"discrete\"",
    "\"default\"",
    "\"table\"",
    "<PROPERTYSTRING>",
    "<WORD>",
    "<LETTER>",
    "<DIGIT>",
    "<NUMBER>",
    "<EXPONENT>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"|\"",
  };

}
