/* Generated By:JavaCC: Do not edit this line. XMLBIFv03Constants.java */
package Parsers.XMLBIFv03;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface XMLBIFv03Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SOT = 3;
  /** RegularExpression Id. */
  int EOT = 4;
  /** RegularExpression Id. */
  int CT = 5;
  /** RegularExpression Id. */
  int OPENTAG = 6;
  /** RegularExpression Id. */
  int EQUAL = 7;
  /** RegularExpression Id. */
  int BIF = 8;
  /** RegularExpression Id. */
  int VERSION = 9;
  /** RegularExpression Id. */
  int FOR = 10;
  /** RegularExpression Id. */
  int GIVEN = 11;
  /** RegularExpression Id. */
  int NAME = 12;
  /** RegularExpression Id. */
  int NETWORK = 13;
  /** RegularExpression Id. */
  int DEFINITION = 14;
  /** RegularExpression Id. */
  int PROPERTY = 15;
  /** RegularExpression Id. */
  int TABLE = 16;
  /** RegularExpression Id. */
  int TYPE = 17;
  /** RegularExpression Id. */
  int OUTCOME = 18;
  /** RegularExpression Id. */
  int VARIABLE = 19;
  /** RegularExpression Id. */
  int NATURE = 20;
  /** RegularExpression Id. */
  int DECISION = 21;
  /** RegularExpression Id. */
  int UTILITY = 22;
  /** RegularExpression Id. */
  int NON_NEGATIVE_NUMBER = 23;
  /** RegularExpression Id. */
  int EXPONENT = 24;
  /** RegularExpression Id. */
  int IDENTIFIER = 25;
  /** RegularExpression Id. */
  int LETTER = 26;
  /** RegularExpression Id. */
  int DIGIT = 27;
  /** RegularExpression Id. */
  int PCDATA_CHARACTER = 28;
  /** RegularExpression Id. */
  int ATTRIBUTE_STRING = 29;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "<token of kind 2>",
    "\"<\"",
    "\"</\"",
    "\">\"",
    "<OPENTAG>",
    "\"=\"",
    "\"BIF\"",
    "\"version\"",
    "\"FOR\"",
    "\"GIVEN\"",
    "\"NAME\"",
    "\"NETWORK\"",
    "\"DEFINITION\"",
    "\"PROPERTY\"",
    "\"TABLE\"",
    "\"TYPE\"",
    "\"OUTCOME\"",
    "\"VARIABLE\"",
    "\"\\\"nature\\\"\"",
    "\"\\\"decision\\\"\"",
    "\"\\\"utility\\\"\"",
    "<NON_NEGATIVE_NUMBER>",
    "<EXPONENT>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<PCDATA_CHARACTER>",
    "<ATTRIBUTE_STRING>",
  };

}
