/* Generated By:JavaCC: Do not edit this line. XMLBIFv02Constants.java */
package Parsers.XMLBIFv02;

/**
 * Token literal values and constants. Generated by
 * org.javacc.parser.OtherFilesGen#start()
 */
public interface XMLBIFv02Constants
{

    /**
     * End of File.
     */
    int EOF = 0;
    /**
     * RegularExpression Id.
     */
    int SOT = 3;
    /**
     * RegularExpression Id.
     */
    int EOT = 4;
    /**
     * RegularExpression Id.
     */
    int CT = 5;
    /**
     * RegularExpression Id.
     */
    int OPENTAG = 6;
    /**
     * RegularExpression Id.
     */
    int BIF = 7;
    /**
     * RegularExpression Id.
     */
    int DEFAUL = 8;
    /**
     * RegularExpression Id.
     */
    int ENTRY = 9;
    /**
     * RegularExpression Id.
     */
    int FOR = 10;
    /**
     * RegularExpression Id.
     */
    int GIVEN = 11;
    /**
     * RegularExpression Id.
     */
    int NAME = 12;
    /**
     * RegularExpression Id.
     */
    int NETWORK = 13;
    /**
     * RegularExpression Id.
     */
    int PROBABILITY = 14;
    /**
     * RegularExpression Id.
     */
    int PROPERTY = 15;
    /**
     * RegularExpression Id.
     */
    int TABLE = 16;
    /**
     * RegularExpression Id.
     */
    int TYPE = 17;
    /**
     * RegularExpression Id.
     */
    int VALUE = 18;
    /**
     * RegularExpression Id.
     */
    int VARIABLE = 19;
    /**
     * RegularExpression Id.
     */
    int DISCRETE = 20;
    /**
     * RegularExpression Id.
     */
    int NON_NEGATIVE_NUMBER = 21;
    /**
     * RegularExpression Id.
     */
    int EXPONENT = 22;
    /**
     * RegularExpression Id.
     */
    int PCDATA_CHARACTER = 23;

    /**
     * Lexical state.
     */
    int DEFAULT = 0;

    /**
     * Literal token values.
     */
    String[] tokenImage =
    {
        "<EOF>",
        "<token of kind 1>",
        "<token of kind 2>",
        "\"<\"",
        "\"</\"",
        "\">\"",
        "<OPENTAG>",
        "\"BIF\"",
        "\"DEFAULT\"",
        "\"ENTRY\"",
        "\"FOR\"",
        "\"GIVEN\"",
        "\"NAME\"",
        "\"NETWORK\"",
        "\"PROBABILITY\"",
        "\"PROPERTY\"",
        "\"TABLE\"",
        "\"TYPE\"",
        "\"VALUE\"",
        "\"VARIABLE\"",
        "\"discrete\"",
        "<NON_NEGATIVE_NUMBER>",
        "<EXPONENT>",
        "<PCDATA_CHARACTER>",
    };

}
